### ISSUE TITLE
does not add labels on reopening

### ISSUE THREAD

**Issue by dogmatic69** [pascalgn/size-label-action#16]
This is an issue for us as we use an automation to create PRs. In order for the CI to run we use another automation to close and re-open the PR (actions workaround for triggering CI when a bot creates PRs).

Net result is that we get no size labels.

Why skip if it is re-opened? Seems there would be no harm in simply allowing this to run.

It is possible to close a PR, push changes to the branch and reopen, this will result in no size change either?

Can [this](https://github.com/pascalgn/size-label-action/blob/master/index.js#L45-L48) be removed or make the options configurable?

**Comment by pascalgn** [comment]
I probably just didn't think about it, so it should be totally fine to add additional events here: https://github.com/pascalgn/size-label-action/blob/master/index.js#L19 Do you want to create a PR for it?

By the way, there is a new event, `workflow_run`, which could maybe help so that the workaround is no longer necessary https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks
